### ISSUE TITLE
Cloning of repo

### ISSUE THREAD

**Issue by zrlhle** [cloudFPGA/cFp_HelloKale#1]
The command to recursively clone the "cFp_HelloKale" repo in section 3.1.3 of the docu fails
- there is a second "-" missing in front of the "recursive" statement
- ssh-based cloning only works if the person has his/her ssh-key in the account
- http-based cloning works without ssh-keys, but then the two repos have to be downloaded independently because the "recursive" option fails

**Comment by fab7** [comment]
- Fixed the missing "-". (Expecting more problems with this MD file which needs to be updated one more time).
- ssh-based cloning: correct, you need to associate an SSH key to your GitHub account (https://docs.github.com/en/authentication/connecting-to-github-with-ssh)

**Comment by zrlhle** [comment]
Please add a comment to this end (need a github account and ssh-key)

**Comment by fab7** [comment]
ABOUT CLONING: cFp_helloKale and its README.md are now configured to allow HTTPS-based cloning.
