### ISSUE TITLE
Step 3 "Add your cloudFPGA credentials" of QuickTrial 3.1.3 may be misleading

### ISSUE THREAD

**Issue by zrlhle** [cloudFPGA/cFp_HelloKale#4]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/11301469/151514111-00cff007-7d79-4d5e-bf0d-131101febf83.png">

The way I understood your guidance was to first create a file named "user.json" and then run the two commands (a procedure which fails miserably, because the first command does not overwrite the `user.json` file I already created). Maybe the guidance should read "In the following step, the two commands below establish and test the user credentials for your cloudFPGA instances. The two commands below result in a file ...",

**Comment by fab7** [comment]
@zrlhle , thanks for assessing the quickstart flow. Some instructions have been added and/or modified with the general idea being to walk the user through the essential steps without going into many details and explanations, but focusing on the workflow.

**Comment by zrlhle** [comment]
Fixed, thank you, closing
