### ISSUE TITLE
"cfsp instance post" command fails with exception 429 "TOO MANY REQUESTS"

### ISSUE THREAD

**Issue by zrlhle** [cloudFPGA/cFp_HelloKale#5]
Exception when calling InstancesApi->cf_manager_rest_api_post_instances: (429)
Reason: TOO MANY REQUESTS
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '0', 'Server': 'Werkzeug/1.0.1 Python/3.6.8', 'Date': 'Fri, 28 Jan 2022 08:40:27 GMT'})

**Comment by diamantopoulos** [comment]
Hi @zrlhle, this is an "expected" error when there is insufficient quota in your project. (if you navigate to http://<swagger_ip>:8080/ui/#/Instances/cf_manager.rest_api.post_instances you can see that the error code 429 corresponds to "Insufficient Quota". 

This means that either you are not part of this group, or there is no fpga available in this group. 

In the former case, you may contact the administrator to add you to a group. 

In the latter case, you need to make sure that no other instances of yours reserve FPGAs (e.g. deled them if you don't need them), or contact again the administrator to increase your quota.

But this might be a common problem, thx for the feedback, maybe we need to add to the documentation @fab7 ? On the other side, this is a notification from the cFRM API and it doesn't make sense to report each of the 100s error/status codes in every project, right? Maybe we can add a notification like: `For a comprehensive list of status/error codes of cFSP, please check cFRM API at http://<swagger_ip>:8080/ui/`

**Comment by zrlhle** [comment]
So it looks like the problem is that my userID "hle" is not associated with any projects ... is the assumption that this association gets done when the user asks for an account? 
@bringlein could you please fix this for me?

**Comment by bringlein** [comment]
@zrlhle yes your account wasn't associated with any cF project, I corrected this just now. 

@diamantopoulos I support the idea to point the user to the swagger UI to check for more details on errors.

**Comment by zrlhle** [comment]
@bringlein thank you, works now
