### ISSUE TITLE
Instructions for TCP/UDP test in section 3.1.3 not clear

### ISSUE THREAD

**Issue by zrlhle** [cloudFPGA/cFp_HelloKale#6]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/11301469/151529677-7ada3218-5ffe-4f16-93bc-bd6fc155ce4e.png">
The current instructions don't make a distinction between the input/output on the command line on one side and the instruction/explanation on the other. Maybe like this ...    
    

> 

     
**Test of TCP-connection**
After you issue the `nc` command below, you can enter an arbitrary text on the console. Once you hit `Return`, the text will be echoed back by the TCP-interface on the cloudFPGA and displayed. You can repeat this several times and end the test with `CTRL-C` 
```
    $ nc <role_ip> 8803
    Hello Kale
    Hello Kale
    ^C
 ```

**Comment by fab7** [comment]
@zrlhle , thanks for assessing the quickstart flow. Some instructions have been added and/or modified with the general idea being to walk the user through the essential steps without going into many details and explanations, but focusing on the workflow.

**Comment by zrlhle** [comment]
Looks good now, thank you, closing
(Detail: may want to replace "Ctlr" with "Ctrl")
